# Generated by Django 2.0.6 on 2020-04-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('counts', models.IntegerField()),
                ('last_time', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.IntegerField()),
            ],
            options={
                'db_table': 'count',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('cate', models.BooleanField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
