# Generated by Django 2.0.6 on 2020-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0003_auto_20200407_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('pics', models.CharField(max_length=20)),
                ('cate', models.BooleanField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
