# Generated by Django 2.0.6 on 2020-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'article_pic',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='pics',
        ),
    ]
