# Generated by Django 2.0.6 on 2020-04-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('broadcast', models.CharField(max_length=20)),
                ('chapter_count', models.IntegerField()),
                ('content', models.TextField()),
                ('score', models.SmallIntegerField()),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('img_src', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('url', models.CharField(max_length=20)),
                ('time_long', models.SmallIntegerField()),
                ('album_id', models.IntegerField()),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
    ]
