# Generated by Django 2.0.6 on 2020-04-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20200413_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img_src',
            field=models.ImageField(max_length=40, upload_to=''),
        ),
    ]
