# Generated by Django 2.0.6 on 2020-04-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20200413_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img_src',
            field=models.ImageField(upload_to='img'),
        ),
    ]
