# Generated by Django 2.0.6 on 2020-04-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('religions_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('salt', models.CharField(max_length=40)),
                ('status', models.BooleanField()),
                ('img_src', models.CharField(max_length=40)),
                ('last_login_time', models.DateTimeField()),
                ('details', models.TextField()),
                ('address', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
