# Generated by Django 2.0.6 on 2020-04-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_src',
            field=models.ImageField(upload_to='user'),
        ),
    ]
