# Generated by Django 2.0.6 on 2020-04-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200409_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
