# Generated by Django 2.0.6 on 2020-04-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200415_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='religions_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
